package-lock.json
tsconfig.json
yarn.lock

Created tsconfig.json file and added it to project

chore: create tsconfig.json file

---

.github/workflows/continous-integration.yml
cypress.config.ts
cypress.d.ts
cypress/component/App.cy.tsx
cypress/e2e/Root.cy.tsx
cypress/support/component-index.html
cypress/support/component.tsx
package.json
tsconfig.json
yarn.lock

add cypress config for end-to-end tests, fix CI pipeline and add end-to-end test scripts

chore: add cypress E2E tests config and fix CI pipeline

---

.github/pull_request_template.md
.prettierignore

create pull request template
it should contain only two sections:
- description
- ticket url

chore: create pull request template

---

cypress/component/AdminPanel/LoginPage.cy.tsx
cypress/component/App.cy.tsx
cypress/e2e/AdminPanel/LoginPage.cy.tsx
cypress/e2e/Root.cy.tsx
cypress/e2e/WrongPath.cy.tsx
src/AdminPanel/modules/LoginPage/LoginPage.tsx
src/App.tsx
src/routes.tsx

create e2e tests for basic routes and component test for admin login page
https://sharing.clickup.com/26492745/t/h/33vay77/UTMW896P46HB04Y

test: create tests for basic routing

---

package.json
yarn.lock

add redux, react-redux and @reduxjs/toolkit to dependencies
https://app.clickup.com/t/33vawpf

chore: add redux

---

.github/pull_request_template.md

fix headers size in pull request template
https://app.clickup.com/t/346qcjz

fix: fix pull request template

---

cypress.config.ts
cypress.d.ts
cypress/component/AdminPanel/LoginPage.cy.tsx
cypress/component/App.cy.tsx
cypress/e2e/AdminPanel/LoginPage.cy.tsx
cypress/e2e/Root.cy.tsx
cypress/e2e/WrongPath.cy.tsx
cypress/support/e2e.tsx
src/App.tsx
src/routes.tsx

add getBySelector command to cypress e2e and component tests, add tests for admin login page and fix already existing tests
https://sharing.clickup.com/26492745/t/h/33vaxyj/HUAHDVP5I1HUFL2

test: tests for admin login page

---

cypress.config.ts
cypress.d.ts
cypress/component/AdminPanel/LoginPage.cy.tsx
cypress/component/App.cy.tsx
cypress/e2e/AdminPanel/LoginPage.cy.tsx
cypress/e2e/Root.cy.tsx
cypress/e2e/WrongPath.cy.tsx
cypress/support/e2e.tsx
package.json
src/AdminPanel/modules/LoginPage/LoginFormFields.tsx
src/AdminPanel/modules/LoginPage/LoginPage.tsx
src/AdminPanel/modules/LoginPage/types.ts
src/AdminPanel/modules/LoginPage/validationSchema.ts
src/App.tsx
src/routes.tsx
yarn.lock

create login to admin page, for now it shouldn't send any http requests on form submit, this will be added in the future
add Yup to dependencies
https://sharing.clickup.com/26492745/t/h/33vaxyj/HUAHDVP5I1HUFL2

feat: create login page to admin panel

---

.github/workflows/continous-integration.yml

fix CI pipeline, it should run on pull request to any branch 
delete cypress component test scripts from pipeline
https://sharing.clickup.com/26492745/t/h/37t7mde/4HG276GCGGMJ0NV

fix: fix CI pipeline

---

package.json
yarn.lock

added mui based on emotion styling engine
https://sharing.clickup.com/26492745/t/h/37z0ve6/DQKME03XO676YOH

chore: add material ui

---

cypress/component/App.cy.tsx

chore: fix-cypress-config-2

---

docs/CONTRIBUTING.md

create contributing guide
it should contain info about how to name branches
types of branches:
- feat
- test
- fix
- docs
- style
- refactor
- build
- chore
- perf
add info about how to merge branches
add info about how to name pull requests
https://app.clickup.com/t/33vaz6n

docs: create contributing guide

---

package.json
vite.config.ts
yarn.lock

add vite-tsconfig-paths to dependencies
add plugin to vite config
https://app.clickup.com/t/384rfg4

build: add vite-tsconfig-paths

---

src/CustomTheme.ts
src/index.tsx
src/theme.ts

create MUI theme, add colors we established we want to use so far
set page background color
[https://sharing.clickup.com/26492745/t/h/384q692/O6PXCYSNFO3046S](https://github.com/UniversityOfGdanskProjects/UI-KIOSK/compare/feat/url)

feat: create MUI theme

---

src/App.tsx
src/components/MainPanel/MainPanel.tsx
src/components/MainPanel/index.tsx
src/index.tsx
src/libs/components/Tile/Tile.tsx
src/libs/components/Tile/index.ts
src/libs/components/index.ts
src/theme.ts
tsconfig.json

create grid based on
https://www.figma.com/file/7y4JIhVwjx4sIQay8yiXCe/kiosk?node-id=0%3A1&t=xMtnxdkCEySw9woI-1
also add libs/components to typescript's custom paths
https://app.clickup.com/t/384rfhv

feat: create layout

---

src/index.tsx
src/store.ts

create redux store
https://app.clickup.com/t/33vax1d

feat: set up redux store

---

cypress.d.ts
cypress/e2e/App.cy.tsx
cypress/e2e/Root.cy.tsx
cypress/support/index.d.ts
cypress/tsconfig.json
cypress/utils/MainPanel/MainPanelTestFunctions.ts
src/components/MainPanel/MainPanel.tsx
tsconfig.json

test MainPanel component
https://app.clickup.com/t/38g0xf4

test: test main panel

---

cypress.d.ts
cypress/e2e/App.cy.tsx
cypress/e2e/Root.cy.tsx
cypress/support/index.d.ts
cypress/tsconfig.json
cypress/utils/MainPanel/MainPanelTestFunctions.ts
package.json
src/App.tsx
src/components/MainPanel/MainPanel.tsx
src/components/MainPanel/index.tsx
src/index.tsx
src/libs/components/Tile/Tile.tsx
src/libs/components/Tile/index.ts
src/libs/components/index.ts
src/theme.ts
tsconfig.json
vite.config.ts
yarn.lock

create grid layout based on 
https://www.figma.com/file/7y4JIhVwjx4sIQay8yiXCe/kiosk?node-id=0%3A1&t=xMtnxdkCEySw9woI-1
for now every tile should be gray without any onClick actions, this will be added in later tasks
https://app.clickup.com/t/33vavvm

feat: create grid layout

---

src/components/MainPanel/MainPanel.tsx
src/libs/components/Tile/Tile.tsx

adjust MainPanel size to new design
https://app.clickup.com/t/38vme98

feat: adjust MainPanel size to new design

---

package.json
yarn.lock

add react i18next do dependencies
https://app.clickup.com/t/38g69ny

build: add react i18next

---

cypress/e2e/AdminPanel/LoginPage.cy.tsx
cypress/e2e/App.cy.tsx
cypress/utils/AdminPanel/LoginPageTestFunctions.ts
cypress/utils/Header/HeaderTestFunctions.ts
cypress/utils/LanguageChange/LanguageChangeTestFunctions.ts
cypress/utils/WelcomePage/WelcomePageTestFunctions.ts
src/AdminPanel/assets/translations/pl.json
src/libs/components/LanguageChange/LanguageChange.tsx

tests for language change
refactor currently existing tests
https://app.clickup.com/t/862hxvgma

test: tests for language change

---

package.json
src/App.tsx
src/components/WelcomePage.tsx/WelcomePage.tsx
src/libs/components/Navbar/Navbar.tsx
src/libs/components/Navbar/index.ts
src/libs/components/index.ts
src/theme.ts
yarn.lock

created bottom navbar 
[https://sharing.clickup.com/26492745/t/h/862j3b4t8/T5BJTRWG5K66Z0I](url)

feat: create navbar

---

cypress.config.ts
cypress/e2e/App.cy.tsx
cypress/e2e/modules/Majors/MajorDetails.cy.ts
cypress/e2e/modules/Majors/MajorsListPage.cy.ts
cypress/fixtures/majors.json
cypress/utils/MainPanel/MainPanelTestFunctions.ts
cypress/utils/modules/Majors/MajoDetailsTestFunctions.ts
cypress/utils/modules/Majors/MajorsListTestFunctions.ts
src/AdminPanel/modules/LoginPage/LoginPage.tsx
src/assets/translations/en.json
src/assets/translations/pl.json
src/components/MainPanel/MainPanel.tsx
src/libs/components/DetailsTile/DetailsTile.tsx
src/libs/components/Divider/Divider.tsx
src/libs/components/ListPageSkeleton/ListPageSkeleton.tsx
src/libs/components/Paragraph/Paragraph.tsx
src/libs/components/Paragraph/index.ts
src/libs/components/Tile/Tile.tsx
src/libs/components/index.ts
src/modules/Majors/MajorDetails/MajorDetailsPage.tsx
src/modules/Majors/MajorsList.tsx
src/modules/Majors/hooks/useGetMajors.ts
src/modules/Majors/hooks/usePrepareMajorDetails.tsx

test majors majors list page and major details page
https://app.clickup.com/t/862j3x890

test: test majors module

---

src/modules/Staff/StaffDetails.tsx
src/modules/Staff/StaffList.tsx
src/modules/Staff/StaffPage.tsx
src/modules/Staff/index.tsx
src/routes.tsx

refactor modules
https://app.clickup.com/t/862jdym9f

refactor: unify modules code

---

docker-compose.yml

Fix docker-compose.yml file
https://sharing.clickup.com/26492745/t/h/862jg7fkz/TIO7XPJXUX6UVO8

fix: fix docker-compose

---

README.md
netlify.toml

Remove `netlify.toml` file and update `README.md` . 
https://sharing.clickup.com/26492745/t/h/862jg237j/KZ4NR8UOON0O35I

chore: remove hosting on netlify
